---
apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    jsonData:
      defaultDatabase: riptide
      port: 9000
      host: clickhouse
      username: default
      tlsSkipVerify: false
    secureJsonData:
      password: ""
