name: Riptide Build
run-name: Build and Test the application
on:
  workflow_dispatch:
  push:
    tags-ignore:
    branches: [ '*' ]
  pull_request_target:
    branches: [ '*' ]
    types: [ opened, synchronize, reopened ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Set up JDK 25 for x64
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version: '25'
          distribution: 'temurin'
          architecture: x64
          cache: maven
      - name: Set version number, data and short git hash
        run: |
          echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> ${GITHUB_ENV}
          echo "SHORT_GIT_SHA=$(git rev-parse --short HEAD)" >> ${GITHUB_ENV}
          echo "BUILD_DATE"=$(date -u +"%Y-%m-%dT%H:%M:%SZ") >> ${GITHUB_ENV}
      - name: Build with tests
        run: |
          make
      - name: Persist JAR artifact
        if: github.event_name != 'pull_request_target'
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: riptide-jar
          path: |
            target/*.jar
