name: Riptide Release
run-name: Build and version release
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 25 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '25'
          distribution: 'temurin'
          architecture: x64
          cache: maven
      - name: Check if you accidentally want to release a SNAPSHOT version
        run: |
          POM_VERSION="$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"
          if [[ "${VERSION}" == *"SNAPSHOT"* ]]; then
            echo "Error: Your pom has a SNAPSHOT release. Set the pom to a version number without SNAPSHOT."
            exit 1
          else
            echo "VERSION=${POM_VERSION}" >> ${GITHUB_ENV}
          fi
      - name: Set data and short git hash
        run: |
          echo "SHORT_GIT_SHA=$(git rev-parse --short HEAD)" >> ${GITHUB_ENV}
          echo "BUILD_DATE"=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
      - name: Build with tests
        run: |
          make
      - name: Persist JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: riptide-jar
          path: |
            target/*.jar
      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push container image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            DATE=${{ env.BUILD_DATE }}
            GIT_SHORT_HASH=${{ env.SHORT_GIT_SHA }}
            REGISTRY_REPOSITORY=riptide-labs
            VERSION=${{ env.VERSION }}
          tags: |
            ghcr.io/riptide-labs/riptide:${{ env.VERSION }}
            ghcr.io/riptide-labs/riptide:latest
      - name: Release ${{ github.ref_name }}
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/*.jar
